### ISSUE TITLE
[BUG] The module hide the buttons from 'Playlist Import' module

### ISSUE THREAD

**Issue by p4535992** [Matthew-Whitlock/FoundryVTT-music-permissions#3]
Issue correlated: https://github.com/JacobMcAuley/playlist_import/issues/49

So i see you made a overwrite of the sidebar html code template ? Can you add a div with the class "directory-footer" ?
Should be enough for solve  this issue.

**Comment by Matthew-Whitlock** [comment]
The newest release solves this, sorry for the delay!
